/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bedrock_and_Breakfast;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author diyatopiwala
 */
public class GuestLoginForm extends javax.swing.JFrame {

    CLIENTS clients = new CLIENTS();
    RESERVATION reservation = new RESERVATION();
    ROOMS rooms = new ROOMS();
    
    int clientsId = 1;
    /**
     * Creates new form GuestLoginForm
     */
    public GuestLoginForm() {
        initComponents();
        displayClientDetails(clientsId);
    }

    //calculate number of nights
    public int calculateNights(Date inDate, Date outDate)  {
        long nights = (outDate.getTime() - inDate.getTime());
        int noNights = (int) (nights / (24 * 60 * 60 * 1000));
        return noNights;
    }
    
    private void displayClientDetails(int id) {
        String[] clientDetails = clients.getClientDetails(id);
        java.sql.Date checkingIn = reservation.getClientCheckInDate(id);
        java.sql.Date checkingOut = reservation.getClientCheckOutDate(id);
        
        int totalNights = calculateNights(checkingIn, checkingOut);
        String nights = String.valueOf(totalNights);
        
        String[] typeInfo = rooms.getTypeInfo(id);
        int roomTypeID = Integer.parseInt(typeInfo[0]);
        int roomPrice = Integer.parseInt(typeInfo[1]);
        String roomName = typeInfo[2];
        int totalPrice = roomPrice * totalNights;
                
        if (clientDetails != null && clientDetails.length == 5) {
            String firstName = clientDetails[0];
            String lastName = clientDetails[1];
            String email = clientDetails[2];
            String phoneNumber = clientDetails[3];
            guestNameLabel.setText(firstName + " " + lastName);
            checkInGuest.setText(checkingIn.toString());
            checkOutGuest.setText(checkingOut.toString());
            numberOfNightsLabel.setText(nights);
            priceLabel.setText("$"+ String.valueOf(totalPrice));
            roomKindLabel.setText(String.valueOf(roomTypeID) + ": "+ roomName);
            emailAddressLabel.setText(email + "?");
            phoneNumberLabel.setText(phoneNumber + "?");
        } else {
            guestNameLabel.setText("Guest");
            checkInGuest.setText("dd/mmm/yyyy");
            checkOutGuest.setText("dd/mmm/yyyy");
            numberOfNightsLabel.setText("0");
            priceLabel.setText("0");
            roomKindLabel.setText("0: none");
            emailAddressLabel.setText("email@address.com?");
            phoneNumberLabel.setText("phone number?");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        st = new javax.swing.JFormattedTextField();
        It = new javax.swing.JFormattedTextField();
        headerLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        checkOutLabel = new javax.swing.JLabel();
        checkOutGuest = new javax.swing.JLabel();
        checkInGuest = new javax.swing.JLabel();
        checkInLabel = new javax.swing.JLabel();
        guestNameLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        nightsLabel = new javax.swing.JLabel();
        numberOfNightsLabel = new javax.swing.JLabel();
        roomTypeLabel = new javax.swing.JLabel();
        roomKindLabel = new javax.swing.JLabel();
        emailButton = new javax.swing.JButton();
        textButton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();
        emailAddressLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        thanksLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        seeYouLabel = new javax.swing.JLabel();

        st.setEditable(false);
        st.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });

        It.setEditable(false);
        It.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        It.setText("check in");
        It.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        headerLabel.setBackground(new java.awt.Color(255, 255, 255));
        headerLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Booking Details");
        headerLabel.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(193, 223, 242));

        checkOutLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        checkOutLabel.setText("Check Out Date:");

        checkOutGuest.setBackground(new java.awt.Color(255, 255, 255));
        checkOutGuest.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        checkOutGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkOutGuest.setText("dd/mmm/yyyy");
        checkOutGuest.setToolTipText("");
        checkOutGuest.setOpaque(true);

        checkInGuest.setBackground(new java.awt.Color(255, 255, 255));
        checkInGuest.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        checkInGuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkInGuest.setText("dd/mmm/yyyy");
        checkInGuest.setToolTipText("");
        checkInGuest.setOpaque(true);

        checkInLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        checkInLabel.setText("Check in Date:");

        guestNameLabel.setFont(new java.awt.Font("Helvetica Neue", 3, 22)); // NOI18N
        guestNameLabel.setText("guest name,");

        welcomeLabel.setBackground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        welcomeLabel.setText("Welcome");

        costLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        costLabel.setText("Cost:");

        priceLabel.setBackground(new java.awt.Color(255, 255, 255));
        priceLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("price");
        priceLabel.setToolTipText("");
        priceLabel.setOpaque(true);

        nightsLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        nightsLabel.setText("Number of Nights:");

        numberOfNightsLabel.setBackground(new java.awt.Color(255, 255, 255));
        numberOfNightsLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        numberOfNightsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOfNightsLabel.setText("nights");
        numberOfNightsLabel.setToolTipText("");
        numberOfNightsLabel.setOpaque(true);

        roomTypeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        roomTypeLabel.setText("Room Selected:");

        roomKindLabel.setBackground(new java.awt.Color(255, 255, 255));
        roomKindLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        roomKindLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomKindLabel.setText("room type");
        roomKindLabel.setToolTipText("");
        roomKindLabel.setOpaque(true);

        emailButton.setText("SEND EMAIL");
        emailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailButtonActionPerformed(evt);
            }
        });

        textButton.setText("SEND TEXT");
        textButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textButtonActionPerformed(evt);
            }
        });

        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setText("Send Email To");

        textLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLabel.setText("Send Text To");

        emailAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailAddressLabel.setText("email@address.com?");

        phoneNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneNumberLabel.setText("phone number?");

        thanksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thanksLabel.setText("Thank you for booking with Bedrock & Breakfast.");

        exitButton.setText("Click to Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        seeYouLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seeYouLabel.setText("See You Soon!!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(welcomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(guestNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(checkOutLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkInLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(costLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nightsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(roomTypeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkInGuest, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(checkOutGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numberOfNightsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(roomKindLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(emailAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(thanksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seeYouLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {checkInGuest, checkOutGuest, numberOfNightsLabel, priceLabel, roomKindLabel});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {emailButton, textButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel)
                    .addComponent(guestNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkInLabel)
                    .addComponent(checkInGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOutLabel)
                    .addComponent(checkOutGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfNightsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nightsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costLabel)
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomKindLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomTypeLabel))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(textLabel))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAddressLabel)
                    .addComponent(phoneNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(thanksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seeYouLabel)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {checkInGuest, checkOutGuest, numberOfNightsLabel, priceLabel, roomKindLabel});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {emailButton, textButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // cannot delete method - ignore
    private void ItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItActionPerformed

    }//GEN-LAST:event_ItActionPerformed

    // cannot delete method - ignore
    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed

    }//GEN-LAST:event_stActionPerformed

    // SHOW SENT TEXT MESSAGE
    private void textButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textButtonActionPerformed
        JOptionPane.showMessageDialog(this, "TEXT SENT!");
    }//GEN-LAST:event_textButtonActionPerformed

    // SHOW SENT EMAIL MESSAGE
    private void emailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailButtonActionPerformed
        JOptionPane.showMessageDialog(this, "EMAIL SENT!");
    }//GEN-LAST:event_emailButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        HomePage homePage = new HomePage();
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestLoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestLoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField It;
    private javax.swing.JLabel checkInGuest;
    private javax.swing.JLabel checkInLabel;
    private javax.swing.JLabel checkOutGuest;
    private javax.swing.JLabel checkOutLabel;
    private javax.swing.JLabel costLabel;
    private javax.swing.JLabel emailAddressLabel;
    private javax.swing.JButton emailButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel guestNameLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nightsLabel;
    private javax.swing.JLabel numberOfNightsLabel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel roomKindLabel;
    private javax.swing.JLabel roomTypeLabel;
    private javax.swing.JLabel seeYouLabel;
    private javax.swing.JFormattedTextField st;
    private javax.swing.JButton textButton;
    private javax.swing.JLabel textLabel;
    private javax.swing.JLabel thanksLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
