/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bedrock_and_Breakfast;

import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariannemasinading
 */
public class ManageRoomsForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageRoomsForm
     */
    ROOMS room = new ROOMS();

    public ManageRoomsForm() {
        initComponents();

        //this is the room type in the button drop down
        room.fillRooms_TYPE_JComboBox(jComboBox_Type);

        //show all rooms in the table
        room.fillRoomsJTable(RoomsTable);

        RoomsTable.setRowHeight(30);

        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonYES);
        bg.add(jRadioButtonNO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Number = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_PhoneNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomsTable = new javax.swing.JTable();
        AddNewRoom_Button = new javax.swing.JButton();
        EditRoomsButton = new javax.swing.JButton();
        RemoveRoomButton = new javax.swing.JButton();
        ClearFieldsButtonRooms = new javax.swing.JButton();
        jComboBox_Type = new javax.swing.JComboBox<>();
        ShowTypes_Button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonYES = new javax.swing.JRadioButton();
        jRadioButtonNO = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1115, 664));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Bedrock & Breakfast");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Manage Rooms");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Number:");

        jTextField_Number.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Number.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextField_Number.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Type:");

        jTextField_PhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_PhoneNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextField_PhoneNumber.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhoneNumberActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Phone No:");

        RoomsTable.setAutoCreateRowSorter(true);
        RoomsTable.setBackground(new java.awt.Color(255, 255, 255));
        RoomsTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RoomsTable.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        RoomsTable.setForeground(new java.awt.Color(0, 0, 0));
        RoomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Type", "Phone", "Reserved"
            }
        )
        {
            public boolean isCellEditable(int row, int column) {
                return false; // All cells are not editable
            }
        }
    );
    RoomsTable.setColumnSelectionAllowed(true);
    RoomsTable.setGridColor(new java.awt.Color(0, 0, 0));
    RoomsTable.setSelectionBackground(new java.awt.Color(204, 204, 255));
    RoomsTable.setShowGrid(true);
    RoomsTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            RoomsTableMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(RoomsTable);
    RoomsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

    AddNewRoom_Button.setBackground(new java.awt.Color(255, 255, 255));
    AddNewRoom_Button.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
    AddNewRoom_Button.setForeground(new java.awt.Color(0, 0, 0));
    AddNewRoom_Button.setText("Add New Room");
    AddNewRoom_Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    AddNewRoom_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    AddNewRoom_Button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            AddNewRoom_ButtonActionPerformed(evt);
        }
    });

    EditRoomsButton.setBackground(new java.awt.Color(255, 255, 255));
    EditRoomsButton.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
    EditRoomsButton.setForeground(new java.awt.Color(0, 0, 0));
    EditRoomsButton.setText("Edit");
    EditRoomsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    EditRoomsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    EditRoomsButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            EditRoomsButtonActionPerformed(evt);
        }
    });

    RemoveRoomButton.setBackground(new java.awt.Color(255, 255, 255));
    RemoveRoomButton.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
    RemoveRoomButton.setForeground(new java.awt.Color(0, 0, 0));
    RemoveRoomButton.setText("Remove");
    RemoveRoomButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    RemoveRoomButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    RemoveRoomButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            RemoveRoomButtonActionPerformed(evt);
        }
    });

    ClearFieldsButtonRooms.setBackground(new java.awt.Color(255, 255, 255));
    ClearFieldsButtonRooms.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
    ClearFieldsButtonRooms.setForeground(new java.awt.Color(0, 0, 0));
    ClearFieldsButtonRooms.setText("Clear Fields");
    ClearFieldsButtonRooms.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    ClearFieldsButtonRooms.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    ClearFieldsButtonRooms.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ClearFieldsButtonRoomsActionPerformed(evt);
        }
    });

    jComboBox_Type.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
    jComboBox_Type.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox_TypeActionPerformed(evt);
        }
    });

    ShowTypes_Button.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
    ShowTypes_Button.setText("Show Types");
    ShowTypes_Button.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ShowTypes_ButtonActionPerformed(evt);
        }
    });

    jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(0, 0, 0));
    jLabel7.setText("Reserved:");

    jRadioButtonYES.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
    jRadioButtonYES.setForeground(new java.awt.Color(0, 0, 0));
    jRadioButtonYES.setText("YES");
    jRadioButtonYES.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jRadioButtonYESActionPerformed(evt);
        }
    });

    jRadioButtonNO.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
    jRadioButtonNO.setForeground(new java.awt.Color(0, 0, 0));
    jRadioButtonNO.setText("NO");
    jRadioButtonNO.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jRadioButtonNOActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBox_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ShowTypes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRadioButtonYES)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jRadioButtonNO))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(306, 306, 306)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(AddNewRoom_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EditRoomsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RemoveRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ClearFieldsButtonRooms, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(84, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jComboBox_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(jTextField_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ShowTypes_Button)
                .addComponent(jLabel6)
                .addComponent(jTextField_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7)
                .addComponent(jRadioButtonYES)
                .addComponent(jRadioButtonNO))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(AddNewRoom_Button)
                .addComponent(EditRoomsButton)
                .addComponent(RemoveRoomButton))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(ClearFieldsButtonRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(15, 15, 15))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1147, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RoomsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomsTableMouseClicked
        // to display the selected row in the textfield

        //display the jtable model
        DefaultTableModel model = (DefaultTableModel) RoomsTable.getModel();

        //get the selected row in the index
        int rowIndex = RoomsTable.getSelectedRow();

        jTextField_Number.setText(model.getValueAt(rowIndex, 0).toString());
        jComboBox_Type.setSelectedItem(model.getValueAt(rowIndex, 1));
        jTextField_PhoneNumber.setText(model.getValueAt(rowIndex, 2).toString());

        String isReserved = model.getValueAt(rowIndex, 3).toString();
        if (isReserved.equals("Yes")) {
            jRadioButtonYES.setSelected(true);
        } else if (isReserved.equals("No")) {
            jRadioButtonNO.setSelected(true);
        }
    }//GEN-LAST:event_RoomsTableMouseClicked

    private void AddNewRoom_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewRoom_ButtonActionPerformed

        try {
            int roomNumber = Integer.valueOf(jTextField_Number.getText());
            int roomType = Integer.valueOf(jComboBox_Type.getSelectedItem().toString());
            String phone = jTextField_PhoneNumber.getText();

            if (room.addRoom(roomNumber, roomType, phone)) {
                JOptionPane.showMessageDialog(rootPane, "New Room Added Successfully", "Add Room", JOptionPane.INFORMATION_MESSAGE);
                //refresh
                room.fillRoomsJTable(RoomsTable);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Room NOT Added", "Add Room Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Room Number", "Room Number Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddNewRoom_ButtonActionPerformed

    private void EditRoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditRoomsButtonActionPerformed

        try {
            int roomNumber = Integer.parseInt(jTextField_Number.getText());;
            int type = Integer.valueOf(jComboBox_Type.getSelectedItem().toString());
            String phone = jTextField_PhoneNumber.getText();
            String isReserved = "No";

            if (jRadioButtonYES.isSelected()) {
                isReserved = "Yes";
            }

            if (phone.trim().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Enter The Room Phone Number", "Empty Fields", JOptionPane.ERROR_MESSAGE);
            } else {
                if (room.editRoom(roomNumber, type, phone, isReserved)) {
                    JOptionPane.showMessageDialog(rootPane, "Room Data Updated Successfully", "Edit Room", JOptionPane.INFORMATION_MESSAGE);
                    // Refresh the JTable data
                    room.fillRoomsJTable(RoomsTable);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Room Data Update Failed", "Update Room Data Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Enter The Room Number", "Room Number Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EditRoomsButtonActionPerformed

    private void RemoveRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveRoomButtonActionPerformed

        int roomNumber;
        try {
            roomNumber = Integer.parseInt(jTextField_Number.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Please Enter a Valid Room Number", "Invalid Room Number", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Confirm the removal action
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to remove this room?", "Remove Room", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            // Remove the room and update the JTable
            if (room.removeRoom(roomNumber)) {
                JOptionPane.showMessageDialog(rootPane, "Room Deleted Successfully", "Delete Room", JOptionPane.INFORMATION_MESSAGE);

                // Clear fields after deletion
                ClearFieldsButtonRoomsActionPerformed(null);

                // Refresh the JTable to show updated data
                room.fillRoomsJTable(RoomsTable);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Room Deletion Failed", "Delete Room Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_RemoveRoomButtonActionPerformed

    private void ClearFieldsButtonRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFieldsButtonRoomsActionPerformed
        jTextField_Number.setText("");
        jTextField_PhoneNumber.setText("");
        jComboBox_Type.setSelectedIndex(0);
        //jRadioButtonYES.setSelected(false);
        jRadioButtonNO.setSelected(true);
    }//GEN-LAST:event_ClearFieldsButtonRoomsActionPerformed

    private void ShowTypes_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTypes_ButtonActionPerformed

        all_room_types_form roomTypesForm = new all_room_types_form();
        roomTypesForm.setVisible(true);
        roomTypesForm.pack();
        roomTypesForm.setLocationRelativeTo(null);
        roomTypesForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_ShowTypes_ButtonActionPerformed

    private void jTextField_PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhoneNumberActionPerformed

    private void jRadioButtonYESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonYESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonYESActionPerformed

    private void jRadioButtonNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNOActionPerformed

    private void jComboBox_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoomsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton AddNewRoom_Button;
    javax.swing.JButton ClearFieldsButtonRooms;
    javax.swing.JButton EditRoomsButton;
    javax.swing.JButton RemoveRoomButton;
    javax.swing.JTable RoomsTable;
    javax.swing.JButton ShowTypes_Button;
    javax.swing.JComboBox<String> jComboBox_Type;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JRadioButton jRadioButtonNO;
    javax.swing.JRadioButton jRadioButtonYES;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextField jTextField_Number;
    javax.swing.JTextField jTextField_PhoneNumber;
    // End of variables declaration//GEN-END:variables
}
